### ISSUE TITLE
Request for CM12 Sources

### ISSUE THREAD

**Issue by SkewedZeppelin** [phenomx4/android_device_zte_nex#1]
Would you mind pushing the CM12 sources if available? Same goes for the kernel.

**Comment by phenomx4** [comment]
Yeah I'll do it tomorrow.

**Comment by SkewedZeppelin** [comment]
Bump.

**Comment by phenomx4** [comment]
I forgot about this. Doing it now.

**Comment by SkewedZeppelin** [comment]
Thanks!
